//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Packages/com.db.gameframework/Input/GameControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace GameFramework
{
    public partial class @GameControls: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @GameControls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameControls"",
    ""maps"": [
        {
            ""name"": ""MainMap"",
            ""id"": ""3cfcb973-9a86-4c6f-98db-580e9607e9dd"",
            ""actions"": [
                {
                    ""name"": ""any"",
                    ""type"": ""Button"",
                    ""id"": ""8c054ff9-7c29-4f3e-91e7-e6d96ea102fe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9a68d8bb-f211-4126-a93c-0577385e256c"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""any"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // MainMap
            m_MainMap = asset.FindActionMap("MainMap", throwIfNotFound: true);
            m_MainMap_any = m_MainMap.FindAction("any", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // MainMap
        private readonly InputActionMap m_MainMap;
        private List<IMainMapActions> m_MainMapActionsCallbackInterfaces = new List<IMainMapActions>();
        private readonly InputAction m_MainMap_any;
        public struct MainMapActions
        {
            private @GameControls m_Wrapper;
            public MainMapActions(@GameControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @any => m_Wrapper.m_MainMap_any;
            public InputActionMap Get() { return m_Wrapper.m_MainMap; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(MainMapActions set) { return set.Get(); }
            public void AddCallbacks(IMainMapActions instance)
            {
                if (instance == null || m_Wrapper.m_MainMapActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_MainMapActionsCallbackInterfaces.Add(instance);
                @any.started += instance.OnAny;
                @any.performed += instance.OnAny;
                @any.canceled += instance.OnAny;
            }

            private void UnregisterCallbacks(IMainMapActions instance)
            {
                @any.started -= instance.OnAny;
                @any.performed -= instance.OnAny;
                @any.canceled -= instance.OnAny;
            }

            public void RemoveCallbacks(IMainMapActions instance)
            {
                if (m_Wrapper.m_MainMapActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IMainMapActions instance)
            {
                foreach (var item in m_Wrapper.m_MainMapActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_MainMapActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public MainMapActions @MainMap => new MainMapActions(this);
        public interface IMainMapActions
        {
            void OnAny(InputAction.CallbackContext context);
        }
    }
}
